services:
  mysql-empleados:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: rrhh_empleados
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [rrhh-network]
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5

  empleados-service:
    build: ./empleados-service
    ports: ['50051:50051']
    environment:
      DB_HOST: mysql-empleados
      DB_USER: root
      DB_PASS: root1234
      DB_NAME: rrhh_empleados
      GRAPHQL_URL: http://proyectos-service:3002/graphql
    depends_on:
      mysql-empleados:
        condition: service_healthy
    networks: [rrhh-network]

  mongo-proyectos:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks: [rrhh-network]

  proyectos-service:
    build: ./proyectos-service
    ports: ['3002:3002']
    environment:
      MONGO_URI: mongodb://mongo-proyectos:27017/rrhh_proyectos
    depends_on: [mongo-proyectos]
    networks: [rrhh-network]

volumes:
  mysql_data:
  mongo_data:

networks:
  rrhh-network:
    driver: bridge